MT5_TERMINAL_PATH = r"C:\Program Files\Pepperstone MetaTrader 5\terminal64.exe"
STOCK_MARKET_CALENDAR = "NYSE"

ROBOFOREX_TIMEZONE = "Europe/Bucharest"

PEPPERSTONE_REFERENCE_TIMEZONE = "America/New_York"
PEPPERSTONE_SERVER_SHIFT_HOURS = 7

